<?= $this->doctype(); ?>
<html lang="pt">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle($this->translate('Application Name') . ' | ' . $this->translate('Application Slug'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>           
        <!-- Le styles -->                               
        <?= $this->headStyle() ?>
        <?=
                $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('/assets/img/favicon.ico')))
                ->headLink(array('rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath('/assets/img/favicon.ico')));
        ?>           
        <!-- Scripts -->        
        <?= $this->headScript() ?>        
    </head>    
    <body class="flat-blue" data-js-libs='<?= $this->requireJsLibs ? json_encode($this->requireJsLibs) : '{}' ?>' data-js-files='<?= $this->requireJsFiles ? json_encode($this->requireJsFiles) : '{}' ?>' style="<?= (!$this->userModel->loggedIn()) ? 'margin-top: 0px;' : '' ?>">        
        <div class="app app-default">                  
            <div class="app-container app-login" data-need-login="true">    
                <div class="flex-center">        
                    <div class="app-header"></div>
                    <div class="app-body">
                        <div class="app-block">    
                            <form id="create-company-form" class="form-horizontal" action="/corporate/conference-business-partner" method="POST" data-svp-id="gmapsstreetviewpano-company" data-svm-id="gmapsstreetviewmap-company">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="form-suggestion">
                                        Selecione quem mais irá assinar em nome da empresa
                                    </div>
                                </div>
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="input-group"> 
                                        <?php foreach ($this->socios AS $socio) { ?>
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox" value="<?= $socio ?>" id="defaultCheck1">
                                                <label class="form-check-label" for="defaultCheck1">
                                                    <?= $socio ?>
                                                </label>
                                            </div>
                                        <?php } ?>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="app-footer">
                        </div>
                    </div>
                </div>
            </div>
            <?= $this->inlineScript() ?>                       
    </body>
</html>                                