<div class="app-container app-login" data-need-login="true">    
    <div class="flex-center">        
        <div class="app-header"></div>
        <div class="app-body">
            <div class="app-block">                
                <div class="app-form">                    
                    <form id="create-company-form" class="form-horizontal" data-success-url="/company" action="/company/create-corporate-user-company.json" method="POST" data-svp-id="gmapsstreetviewpano-company" data-svm-id="gmapsstreetviewmap-company">
                        <div class="row">
                            <div class="form-suggestion">
                                <?= $this->translate('Conference business partner'); ?>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                <div class="input-group">
                                    <span class="input-group-addon" id="basic-addon3">Vimos que existem outros sócios...</span>
                                    <span class="input-group-addon" id="basic-addon3">Vocês assinam em conjunto?</span>
                                    <label class="radio-inline"><input type="radio" name="optradio">Option 1</label>
                                    <label class="radio-inline"><input type="radio" name="optradio">Option 2</label>

                                </div>
                            </div>                            
                    </form>
                </div>
            </div>
        </div>
        <div class="app-footer">
        </div>
    </div>
</div>