<div class="app-container app-login" data-need-login="true">    
    <div class="flex-center">        
        <div class="app-header"></div>
        <div class="app-body">
            <div class="app-block">                
                <div class="app-form">                    
                    <form id="create-company-form" class="form-horizontal" data-success-url="/company" action="/company/create-corporate-user-company.json" method="POST" data-svp-id="gmapsstreetviewpano-company" data-svm-id="gmapsstreetviewmap-company">
                        <div class="row">
                            <div class="form-suggestion">
                                <?= $this->translate('Conference business partner'); ?>
                            </div>                            
                            <div class="form-suggestion">Vimos que existem outros sócios...</div>
                            <div class="form-suggestion">Vocês assinam em conjunto?</div>
                            <div class="input-group">
                                <label class="radio-inline"><input type="radio" name="optradio">Sim</label>
                                <label class="radio-inline"><input type="radio" name="optradio">Não, eu assino sozinho pela companhia</label>
                            </div>

                    </form>
                </div>
            </div>
        </div>
        <div class="app-footer">
        </div>
    </div>
</div>