<?= $this->doctype(); ?>
<html lang="pt">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle($this->translate('Application Name') . ' | ' . $this->translate('Application Slug'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>           
        <!-- Le styles -->                               
        <?= $this->headStyle() ?>
        <?=
                $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('/assets/img/favicon.ico')))
                ->headLink(array('rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath('/assets/img/favicon.ico')));
        ?>           
        <!-- Scripts -->        
        <?= $this->headScript() ?>        
    </head>    
    <body class="flat-blue" data-js-libs='<?= $this->requireJsLibs ? json_encode($this->requireJsLibs) : '{}' ?>' data-js-files='<?= $this->requireJsFiles ? json_encode($this->requireJsFiles) : '{}' ?>' style="<?= (!$this->userModel->loggedIn()) ? 'margin-top: 0px;' : '' ?>">        
        <div class="app app-default">                  
            <div class="app-container app-login" data-need-login="true">    
                <div class="flex-center">        
                    <div class="app-header"></div>
                    <div class="app-body">
                        <div class="app-block">                
                            <div class="app-form">

                                <span>Você possui Procuração para Representar a Empresa?</span>
                                <div class="radio">
                                    <label><input id="procuracao-sim" type="radio" name="optradio">Sim</label>
                                </div>
                                <div class="radio">
                                    <label><input id="procuracao-nao" type="radio" name="optradio">Não</label>
                                </div>
                                <div id="enviar-procuracao" style="display:none">
                                    <span>Neste caso nos envie sua procuração</span>
                                    <form action="/corporate/create-procuration" method="POST">
                                        <input type="hidden" name="create-procuration" value="true">
                                        <input type="file">
                                        <button type="submit" class="btn btn-success btn-submit">Enviar procuração</button>
                                    </form>
                                </div>                                
                                <div id="gerar-procuracao" style="display:none">
                                    <span>Neste caso vamos criar uma nova procuração</span>
                                    <form action="/corporate/create-procuration" method="POST">
                                        <input type="hidden" name="create-procuration" value="true">
                                        <embed src="https://sistemas.mre.gov.br/kitweb/datafiles/Frankfurt/pt-br/file/ModelosGeraisProcuraçõesPúblicas.pdf" width="100%" height="500" alt="pdf" pluginspage="http://www.adobe.com/products/acrobat/readstep2.html">
                                        <button type="submit" class="btn btn-success btn-submit">Assinar procuração</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="app-footer">
                        </div>
                    </div>
                </div>
            </div>
            <?= $this->inlineScript() ?>  
            <script>
                var sim = document.querySelector("#procuracao-sim");
                var nao = document.querySelector("#procuracao-nao");
                nao.addEventListener("click", function () {
                    document.querySelector('#enviar-procuracao').style.display = 'none';
                   document.querySelector('#gerar-procuracao').style.display = 'block';
                });
                sim.addEventListener("click", function () {
                    document.querySelector('#gerar-procuracao').style.display = 'none';
                    document.querySelector('#enviar-procuracao').style.display = 'block';
                });

            </script>
    </body>
</html>                                